lang_codes = {
  'ab': 'Abkhaz',
  'aa': 'Afar',
  'af': 'Afrikaans',
  'ak': 'Akan',
  'sq': 'Albanian',
  'am': 'Amharic',
  'ar': 'Arabic',
  'an': 'Aragonese',
  'hy': 'Armenian',
  'as': 'Assamese',
  'av': 'Avaric',
  'ae': 'Avestan',
  'ay': 'Aymara',
  'az': 'Azerbaijani',
  'bm': 'Bambara',
  'ba': 'Bashkir',
  'eu': 'Basque',
  'be': 'Belarusian',
  'bn': 'Bengali',
  'bh': 'Bihari',
  'bi': 'Bislama',
  'bs': 'Bosnian',
  'br': 'Breton',
  'bg': 'Bulgarian',
  'my': 'Burmese',
  'ca': 'Catalan; Valencian',
  'ch': 'Chamorro',
  'ce': 'Chechen',
  'ny': 'Chichewa; Chewa; Nyanja',
  'zh': 'Chinese',
  'cv': 'Chuvash',
  'kw': 'Cornish',
  'co': 'Corsican',
  'cr': 'Cree',
  'hr': 'Croatian',
  'cs': 'Czech',
  'da': 'Danish',
  'dv': 'Divehi; Maldivian;',
  'nl': 'Dutch',
  'dz': 'Dzongkha',
  'en': 'English',
  'eo': 'Esperanto',
  'et': 'Estonian',
  'ee': 'Ewe',
  'fo': 'Faroese',
  'fj': 'Fijian',
  'fi': 'Finnish',
  'fr': 'French',
  'ff': 'Fula',
  'gl': 'Galician',
  'ka': 'Georgian',
  'de': 'German',
  'el': 'Greek, Modern',
  'gn': 'Guaraní',
  'gu': 'Gujarati',
  'ht': 'Haitian',
  'ha': 'Hausa',
  'he': 'Hebrew modern)',
  'hz': 'Herero',
  'hi': 'Hindi',
  'ho': 'Hiri Motu',
  'hu': 'Hungarian',
  'ia': 'Interlingua',
  'id': 'Indonesian',
  'ie': 'Interlingue',
  'ga': 'Irish',
  'ig': 'Igbo',
  'ik': 'Inupiaq',
  'io': 'Ido',
  'is': 'Icelandic',
  'it': 'Italian',
  'iu': 'Inuktitut',
  'ja': 'Japanese',
  'jv': 'Javanese',
  'kl': 'Kalaallisut',
  'kn': 'Kannada',
  'kr': 'Kanuri',
  'ks': 'Kashmiri',
  'kk': 'Kazakh',
  'km': 'Khmer',
  'ki': 'Kikuyu, Gikuyu',
  'rw': 'Kinyarwanda',
  'ky': 'Kirghiz, Kyrgyz',
  'kv': 'Komi',
  'kg': 'Kongo',
  'ko': 'Korean',
  'ku': 'Kurdish',
  'kj': 'Kwanyama, Kuanyama',
  'la': 'Latin',
  'lb': 'Luxembourgish',
  'lg': 'Luganda',
  'li': 'Limburgish',
  'ln': 'Lingala',
  'lo': 'Lao',
  'lt': 'Lithuanian',
  'lu': 'Luba-Katanga',
  'lv': 'Latvian',
  'gv': 'Manx',
  'mk': 'Macedonian',
  'mg': 'Malagasy',
  'ms': 'Malay',
  'ml': 'Malayalam',
  'mt': 'Maltese',
  'mi': 'Māori',
  'mr': 'Marathi Marāṭhī)',
  'mh': 'Marshallese',
  'mn': 'Mongolian',
  'na': 'Nauru',
  'nv': 'Navajo, Navaho',
  'nb': 'Norwegian Bokmål',
  'nd': 'North Ndebele',
  'ne': 'Nepali',
  'ng': 'Ndonga',
  'nn': 'Norwegian Nynorsk',
  'no': 'Norwegian',
  'ii': 'Nuosu',
  'nr': 'South Ndebele',
  'oc': 'Occitan',
  'oj': 'Ojibwe, Ojibwa',
  'cu': 'Old Church Slavonic',
  'om': 'Oromo',
  'or': 'Oriya',
  'os': 'Ossetian, Ossetic',
  'pa': 'Panjabi, Punjabi',
  'pi': 'Pāli',
  'fa': 'Persian',
  'pl': 'Polish',
  'ps': 'Pashto, Pushto',
  'pt': 'Portuguese',
  'qu': 'Quechua',
  'rm': 'Romansh',
  'rn': 'Kirundi',
  'ro': 'Romanian, Moldavan',
  'ru': 'Russian',
  'sa': 'Sanskrit Saṁskṛta)',
  'sc': 'Sardinian',
  'sd': 'Sindhi',
  'se': 'Northern Sami',
  'sm': 'Samoan',
  'sg': 'Sango',
  'sr': 'Serbian',
  'gd': 'Scottish Gaelic',
  'sn': 'Shona',
  'si': 'Sinhala, Sinhalese',
  'sk': 'Slovak',
  'sl': 'Slovene',
  'so': 'Somali',
  'st': 'Southern Sotho',
  'es': 'Spanish; Castilian',
  'su': 'Sundanese',
  'sw': 'Swahili',
  'ss': 'Swati',
  'sv': 'Swedish',
  'ta': 'Tamil',
  'te': 'Telugu',
  'tg': 'Tajik',
  'th': 'Thai',
  'ti': 'Tigrinya',
  'bo': 'Tibetan',
  'tk': 'Turkmen',
  'tl': 'Tagalog',
  'tn': 'Tswana',
  'to': 'Tonga',
  'tr': 'Turkish',
  'ts': 'Tsonga',
  'tt': 'Tatar',
  'tw': 'Twi',
  'ty': 'Tahitian',
  'ug': 'Uighur, Uyghur',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'uz': 'Uzbek',
  've': 'Venda',
  'vi': 'Vietnamese',
  'vo': 'Volapük',
  'wa': 'Walloon',
  'cy': 'Welsh',
  'wo': 'Wolof',
  'fy': 'Western Frisian',
  'xh': 'Xhosa',
  'yi': 'Yiddish',
  'yo': 'Yoruba',
  'za': 'Zhuang, Chuang',
  'zu': 'Zulu',
  'xx': 'Multi-language'
}

code_to_native = {
  "ab": "Aҧсуа",
  "aa": "Afaraf",
  "af": "Afrikaans",
  "ak": "Akan",
  "sq": "Shqip",
  "am": "አማርኛ",
  "ar": "العربية",
  "an": "Aragonés",
  "hy": "Հայերեն",
  "as": "অসমীয়া",
  "av": "Aвар мацӀ",
  "ae": "Avesta",
  "ay": "Aymar aru",
  "az": "Azərbaycan dili",
  "bm": "Bamanankan",
  "ba": "башҡорт теле",
  "eu": "Euskara",
  "be": "Беларуская",
  "bn": "বাংলা",
  "bh": "भोजपुरी",
  "bi": "Bislama",
  "bs": "Bosanski jezik",
  "br": "Brezhoneg",
  "bg": "български език",
  "my": "ဗမာစာ",
  "ca": "Català",
  "ch": "Chamoru",
  "ce": "нохчийн мотт",
  "ny": "chiCheŵa, chinyanja",
  "zh": "中文",
  "cv": "чӑваш чӗлхи",
  "kw": "Kernewek",
  "co": "Corsu",
  "cr": "ᓀᐦᐃᔭᐍᐏᐣ",
  "hr": "Hrvatski",
  "cs": "Česky",
  "da": "Dansk",
  "dv": "ދިވެހި",
  "nl": "Nederlands",
  "en": "English",
  "eo": "Esperanto",
  "et": "Eesti",
  "ee": "Eʋegbe",
  "fo": "Føroyskt",
  "fj": "Vosa Vakaviti",
  "fi": "Suomi",
  "fr": "Français",
  "ff": "Fulfulde",
  "gl": "Galego",
  "ka": "ქართული",
  "de": "Deutsch",
  "el": "Ελληνικά",
  "gn": "Avañeẽ",
  "gu": "ગુજરાતી",
  "ht": "Kreyòl ayisyen",
  "ha": "Hausa",
  "he": "עברית",
  "hz": "Otjiherero",
  "hi": "हिन्दी, हिंदी",
  "ho": "Hiri Motu",
  "hu": "Magyar",
  "ia": "Interlingua",
  "id": "Bahasa Indonesia",
  "ie": "Interlingue",
  "ga": "Gaeilge",
  "ig": "Asụsụ Igbo",
  "ik": "Iñupiaq",
  "io": "Ido",
  "is": "Íslenska",
  "it": "Italiano",
  "iu": "ᐃᓄᒃᑎᑐᑦ",
  "ja": "日本語",
  "jv": "Basa Jawa",
  "kl": "Kalaallisut",
  "kn": "ಕನ್ನಡ",
  "kr": "Kanuri",
  "ks": "कश्मीरी",
  "kk": "Қазақ тілі",
  "km": "ភាសាខ្មែរ",
  "ki": "Gĩkũyũ",
  "rw": "Ikinyarwanda",
  "ky": "кыргыз тили",
  "kv": "коми кыв",
  "kg": "KiKongo",
  "ko": "한국어",
  "ku": "Kurdî",
  "kj": "Kuanyama",
  "la": "Latine",
  "lb": "Lëtzebuergesch",
  "lg": "Luganda",
  "li": "Limburgs",
  "ln": "Lingála",
  "lo": "ພາສາລາວ",
  "lt": "Lietuvių kalba",
  "lu": "Kiluba",
  "lv": "Latviešu valoda",
  "gv": "Gaelg, Gailck",
  "mk": "македонски јазик",
  "mg": "Malagasy fiteny",
  "ms": "Bahasa Melayu",
  "ml": "മലയാളം",
  "mt": "Malti",
  "mi": "te reo Māori",
  "mr": "मराठी",
  "mh": "Kajin M̧ajeļ",
  "mn": "монгол",
  "na": "Ekakairũ Naoero",
  "nv": "Diné bizaad",
  "nb": "Norsk bokmål",
  "nd": "isiNdebele",
  "ne": "नेपाली",
  "ng": "Owambo",
  "nn": "Norsk nynorsk",
  "no": "Norsk",
  "ii": "ꆈꌠ꒿ Nuosuhxop",
  "nr": "isiNdebele",
  "oc": "Occitan",
  "oj": "ᐊᓂᔑᓈᐯᒧᐎᓐ",
  "cu": "ѩзыкъ словѣньскъ",
  "om": "Afaan Oromoo",
  "or": "ଓଡ଼ିଆ",
  "os": "ирон æвзаг",
  "pa": "ਪੰਜਾਬੀ",
  "pi": "पाऴि",
  "fa": "فارسی",
  "pl": "Polski",
  "ps": "پښتو",
  "pt": "Português",
  "qu": "Runa Simi",
  "rm": "rumantsch grischun",
  "rn": "kiRundi",
  "ro": "Română",
  "ru": "русский язык",
  "sa": "संस्कृतम्",
  "sc": "Sardu",
  "sd": "सिन्धी",
  "se": "Davvisámegiella",
  "sm": "Gagana faa Samoa",
  "sg": "yângâ tî sängö",
  "sr": "српски језик",
  "gd": "Gàidhlig",
  "sn": "chiShona",
  "si": "සිංහල",
  "sk": "slovenčina",
  "sl": "slovenščina",
  "so": "Soomaaliga",
  "st": "Sesotho",
  "es": "Español",
  "su": "Basa Sunda",
  "sw": "Kiswahili",
  "ss": "SiSwati",
  "sv": "svenska",
  "ta": "தமிழ்",
  "te": "తెలుగు",
  "tg": "тоҷикӣ",
  "th": "ไทย",
  "ti": "ትግርኛ",
  "bo": "བོད་ཡིག",
  "tk": "Türkmen, Түркмен",
  "tl": "Wikang Tagalog",
  "tn": "Setswana",
  "to": "faka Tonga",
  "tr": "Türkçe",
  "ts": "Xitsonga",
  "tt": "татарча",
  "tw": "Twi",
  "ty": "Reo Tahiti",
  "ug": "Uyƣurqə",
  "uk": "українська",
  "ur": "اردو",
  "uz": "Zbek",
  "ve": "Tshivenḓa",
  "vi": "Tiếng Việt",
  "vo": "Volapük",
  "wa": "Walon",
  "cy": "Cymraeg",
  "wo": "Wollof",
  "fy": "Frysk",
  "xh": "isiXhosa",
  "yi": "ייִדיש",
  "yo": "Yorùbá",
  "za": "Saɯ cueŋƅ",
  'xx': 'Multi-language'
}
